spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}

spring.application.name=ExpenseTrackerApi
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#enable all endpoints of actuator
management.endpoints.web.exposure.include=*

jwt.secret=${JWT_SECRET}
jwt.expiry=${JWT_EXPIRY}

admin.fullName=${ADMIN_FULL_NAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}