spring.application.name=ExpenseTrackerApi
spring.datasource.url=jdbc:postgresql://localhost:5432/sping_expense_tracker
spring.datasource.username=postgres
spring.datasource.password=root

server.servlet.context-path=/api/v1

#disable in production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#enable all endpoints of actuator
management.endpoints.web.exposure.include=*


jwt.secret=MyVeryStrongSecretKeyForJwtAuthentication12345
jwt.expiry=86400000